dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy2.7-5.8.0"
  - "pypy2.7-5.9.0"
  - "pypy3.5-5.8.0"
  - "pypy3.5-5.9.0"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: coverage run --source=digitalocean setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: joamag
  password:
    secure: KC6x6g52mSpOozxS4B4sDvV+ocNa2IfM/Z9lw21fHPHE0otWxS5avb+bJx4/9Kid85EMpclPoM7rKc5EGWE54TXAnTGpMuqEcbjJ9gWf0DCz6n9thleT0OnHxYVi+Px7ut++jVrGH1InW2hWo9GC4MiXXiH7QLJklNgO+mxrR4U=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
