dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=digitalocean setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: KC6x6g52mSpOozxS4B4sDvV+ocNa2IfM/Z9lw21fHPHE0otWxS5avb+bJx4/9Kid85EMpclPoM7rKc5EGWE54TXAnTGpMuqEcbjJ9gWf0DCz6n9thleT0OnHxYVi+Px7ut++jVrGH1InW2hWo9GC4MiXXiH7QLJklNgO+mxrR4U=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
